### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by joseahr** [oscarfonts/docker-geoserver#10]
Hi guys! I had problems setting up the environment with the new configuration for deploying in Elastic Beanstalk. I successfully resolved this issues and I left it here the solution:

Problems:
  - **The mount part of the file system failed**.
    This was due to the instances generated by EB did not have the default security group of the FileSystem associated. We need to select it when launching the environment.

  - **Log in was not possible (and/or entire GUI was failing)**
    This was due to the session not being persisted across the instances. We need to enable session stickyness.

I also checked the "Load balancing across multiple Availability Zones enabled" because  instances are created in different Availavility Zones.

Now the environment seems to work correctly. Load Balancing is balancing my requests correctly, but the requests made from the GUI are balanced to the same instance keeping the session.

Did you follow this configuration? I'm missing something? If this is okey, it would be great to have a note for future readers.

----
Thank you!

**Comment by victorzinho** [comment]
Hi @joseahr. Yes, that's the proper configuration to make it work.

The doc about creating the environment is pretty scarce because we assume all configuration details are known by the user, but your notes are very useful. I just added them to the doc. Thanks for the contribution!
