### ISSUE TITLE
ERROR [geoserver.logging] - Could not configure log4j overrides

### ISSUE THREAD

**Issue by ducat7** [oscarfonts/docker-geoserver#12]
OS：Win_7
Docker：boot2docker_18.09.3
Docker Compose file：docker-compose_gis.yml
```
version: "3"


services:
  GeoServer:
    restart: always
    tty: true
    image: oscarfonts/geoserver
    environment:
      TZ: Asia/Shanghai
    volumes:
      # ERROR [geoserver.logging] - Could not configure log4j overrides
      - /usr/local/GeoServer/node/data:/var/local/geoserver:z
    ports:
      - "5080:8080"
    deploy:
      replicas: 1
```
Command：docker-compose -f docker-compose_gis.yml -p gis up -d --force-recreate

Create the container success, But, Docker logs errors：
ERROR [geoserver.logging] - Could not configure log4j overrides

1、I have closed volumes configured with no errors occurred。
2、I have：
```
docker-machine ssh
sudo mkdir -m 777 -p /usr/local/GeoServer/node/data && sudo chown -R root:staff /usr/local/GeoServer/node/data
```
This does not help。

This how to deal with it?

**Comment by jbarcelo3** [comment]
Similar problem here. When running startup.bat, the console says 'could not configure log4j overrides'. However, there seems to be a previous problem loading an environment variable. Do you receive that warning? Have you tried to fix it?

**Comment by wint3ria** [comment]
Same problem here

**Comment by Anmoldeep1509** [comment]
Same problem here, will see more if I can find a solution, and then will post here if found.

**Comment by jorgejesus** [comment]
This seems to be cause by the usage of a specific user running tomcat/geoserver  ([here](https://github.com/oscarfonts/docker-geoserver/blob/249a9758853a98986d66b67e39431852f5e1bb0c/2.19.0/Dockerfile#L56)). Remove the user creation and the problem is solved. 

But we loose specific user ID running the container, this may raise other problems (e.g Openshift)
