### ISSUE TITLE
Cors seem not working 

### ISSUE THREAD

**Issue by lchunleo** [oscarfonts/docker-geoserver#16]
Hi
I having some cors issue. I noted that your Web.xml have the cors filter but somehow I kept getting cors error. I have disable my chrome security and found I am able to access the geoserver. 

Can I check which path is the correct Web.xml as there are a few Web.xml in your docker? Can you teach me how to patch or resolve this issue? Is there anything to do with the secuity settings? Thanks

**Comment by romaintha** [comment]
I observed the same issue.

**Comment by oscarfonts** [comment]
We added a way to control CORS headers via environment variables and a section in the README file describing its usage.
