### ISSUE TITLE
adding mapfish-print

### ISSUE THREAD

**Issue by mmeinert** [oscarfonts/docker-geoserver#2]
I'd like to add [mapfish-print](http://docs.geoserver.org/latest/en/user/extensions/printing/) tool to this instance but can't find the geoserver/WEB-INF/lib folder to place the archive.
How can I expose a local folder to place geoserver's extensions ?

**Comment by oscarfonts** [comment]
You'd have to build your own custom image.
See for instance the ``2.8.x-h2`` branch, which installs the h2 extension on top of GeoServer base:
https://github.com/oscarfonts/docker-geoserver/blob/2.8.x-h2/Dockerfile

Please refer to Docker documentation for further detail. :)
