### ISSUE TITLE
Enable ECW

### ISSUE THREAD

**Issue by beachwalker** [oscarfonts/docker-geoserver#28]
How to enable ECW?

**Comment by yang9511** [comment]
ecw 27lines："&& ln -s /usr/local/java/gdal.jar ${GEOSERVER_INSTALL_DIR}/WEB-INF/lib"，
should be “&& cp /usr/local/java/gdal.jar ${GEOSERVER_INSTALL_DIR}/WEB-INF/lib”
i think

**Comment by oscarfonts** [comment]
We don't support ECW for this image. It needs a special GDAL build.

There's an unsupported Dockerfile sample in this repo, which worked with older versions of geoserver, but it's unmaintained right now.
