### ISSUE TITLE
Wrong command in docker page?

### ISSUE THREAD

**Issue by fergonco** [oscarfonts/docker-geoserver#5]
in the docker hub page ( https://hub.docker.com/r/oscarfonts/geoserver/), section "Running", first command:
`docker run -d -p 8080:8080 -v /path/to/local/data_dir:/var/local/geoserver localhost --name=MyGeoServerInstance oscarfonts/geoserver`

had to remove "localhost" to get it working.

**Comment by oscarfonts** [comment]
References to localhost were added here:

https://github.com/oscarfonts/docker-geoserver/commit/a1865d9099e378f2e06d50fb1842e6c34611d276#diff-04c6e90faac2675aa89e2176d2eec7d8R58

https://github.com/oscarfonts/docker-geoserver/commit/4ff5907c0a4c46c8575fae654ae33792365321ce#diff-04c6e90faac2675aa89e2176d2eec7d8R37

Looks like a bug to me. @victorzinho are we safe to remove them?

**Comment by victorzinho** [comment]
Yep, totally a bug.
