### ISSUE TITLE
Handle geoserver sample data/layers

### ISSUE THREAD

**Issue by eblondel** [oscarfonts/docker-geoserver#6]
Hello @oscarfonts , is there a way to run this geoserver docker image with the geoserver "traditional" sample data (that comes usually with Geoserver)? Many thanks in advance

**Comment by oscarfonts** [comment]
@eblondel the sample data lives inside the container, and should work by default. Just run the container without the volume mapping (-v parameter).

Just tested it:
```
docker run -d -p 8080:8080 oscarfonts/geoserver
```

And it worked:
![screenshot from 2017-03-02 09-48-05](https://cloud.githubusercontent.com/assets/485651/23499818/f3f4f520-ff2d-11e6-9365-cbe914f7dd66.png)

**Comment by eblondel** [comment]
Thanks @oscarfonts !
