### ISSUE TITLE
Configure extensions when deploying to EB

### ISSUE THREAD

**Issue by joseahr** [oscarfonts/docker-geoserver#8]
Is it possible to configure the extensions when deploying to Elastic Beanstalk?

**Comment by victorzinho** [comment]
Yes, you would need to:

* Add your extensions to your EBS volume (in an `exts` directory, for example) (see [doc](https://github.com/oscarfonts/docker-geoserver#configure-extensions) for more info about the extensions directory).
* Mount your directory containing the extensions in `/var/local/geoserver-exts/`, in the `Dockerrun.aws.json` file:

```
{
  ...
  "Volumes": [
    ...
    {
      "HostDirectory": "/mnt/geoserver/exts",
      "ContainerDirectory": "/var/local/geoserver-exts"
    }
  ]
}
```
