### ISSUE TITLE
Missing community plugins for 2.13.x

### ISSUE THREAD

**Issue by Trashmonk** [oscarfonts/docker-geoserver#9]
I tried running build_exts_dir.sh and I get the following error:

--2018-07-16 14:16:12--  http://ares.boundlessgeo.com/geoserver/2.13.x/community-latest//geoserver-2.13-SNAPSHOT-geofence-plugin.zip
Resolving ares.boundlessgeo.com (ares.boundlessgeo.com)... 108.178.11.4
Connecting to ares.boundlessgeo.com (ares.boundlessgeo.com)|108.178.11.4|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-07-16 14:16:12 ERROR 404: Not Found.

When I go to http://ares.boundlessgeo.com/geoserver/ there is no 2.13x folder, it looks like the website hasn't been updated since late 2017.

I also went to https://build.geoserver.org/geoserver/master/community-latest to see if I could get the community plugins from there, the website is down. Any suggestions?

**Comment by victorzinho** [comment]
This is because there is no [Geofence](https://github.com/geoserver/geofence#getting-geofence) extension for GeoServer 2.13.x. Either you use 2.12.x or you edit the extensions file to remove geofence.

**Comment by Trashmonk** [comment]
SO,  https://build.geoserver.org/geoserver/master/community-latest is back up, so I just swapped out  http://ares.boundlessgeo.com/geoserver/ with https://build.geoserver.org/geoserver/ on line 56 of build_exts_dir.sh this fixed the issue. Geofence is available for 2.13 from this link.
